### ISSUE TITLE
Pretrained models for Chexpert dataset

### ISSUE THREAD

**Issue by smnai** [JuliaWolleb/DeScarGAN#3]
Hi, 
Would you be able to share the pretrained models for the Chexpert dataset?

Thanks for releasing the code for this nice project :)

**Comment by JuliaWolleb** [comment]
Hi,

I had some issues uploading the files to Github, they were too big. Here is the link to a google drive folder containing the pretrained nets for the generator and discriminator for the Chexpert dataset:

https://drive.google.com/drive/folders/1xaSEpBZuJwZ12-e3-_RYTFI_TBdfvpvj

Let me know whether it worked like this :)

**Comment by smnai** [comment]
Perfect, many thanks for this !!!
