### ISSUE TITLE
Chexpert input images shape

### ISSUE THREAD

**Issue by smnai** [JuliaWolleb/DeScarGAN#4]
What shape should the .npy chexpert images have to be used for training and testing? 

Thanks :)

**Comment by JuliaWolleb** [comment]
Hi,

When you check the shape of "inputs" in line 201 of the file _model/DeScarGAN.py_, you should get the shape [batchsize, 1,256,256]. That's what you send through the network.
For training, I had batchsize=10, and for testing it is only batchsize=1.

Does this answer your question?

**Comment by smnai** [comment]
Hmm so, each .npy image in the dataset should have shape (256,256,1), right?

**Comment by JuliaWolleb** [comment]
yes, exactly

**Comment by smnai** [comment]
Perfect, thanks 👍
