### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by zzl777** [JuliaWolleb/DeScarGAN#5]
1. about dataset 
what is the type of the data set ?
2.  requirements
can you list the requirements(including the vision of python, pytorch, etc.)
thanks

**Comment by JuliaWolleb** [comment]
Hi

1. What do you mean by type of dataset? The images are saved in the .npy format, and they are all of size (256,256,1).

2. Yes, of course:
                                                                                                                                                                                                                                                                                                                                                             apex                      0.1                     
itk                         5.0.1                           
nipype                  1.2.0 
numpy                  1.19.2              
pandas                  1.0.3                                            
Pillow                    6.2.1              
pip                        20.2.4   
python                  3.6            
python-utils          2.3.0                                                                                           
pytorch-msssim    0.1.5                
scikit-learn            0.23.2                                                                                          
scipy                     1.5.2                                                                                           
seaborn                0.10.1                 
setuptools            50.3.0.post20201006          
Shapely                1.6.4.post2                                                                                    
SimpleITK             1.2.2     
torch                     1.5.0
torchvision            0.6.0a0+82fd1c8
